# 
# Sunbeam configuration file
#
# Paths:
#   Paths are resolved through the following rules:
#     1. If the path is absolute, the path is parsed as-is
#     2. If the path is not absolute, the path at 'root' is appended to it
#     3. If the path is not 'output_fp', the path is checked to ensure it exists
#
# Suffixes:
#   Each subsection contains a 'suffix' key that defines the folder under
#   'output_fp' where the results of that section are put.
#

# General options

all:
  root: "/home/zhaoc1/path/to/your/project/dir"
  data_fp: "data_files"
  output_fp: "sunbeam_output"
  filename_fmt: "PCMP_{sample}_{rp}.fastq"
  subcores: 4
  exclude: []


# Quality control
qc:
  suffix: qc
  # Trimmomatic
  threads: 8
  java_heapsize: 512M
  leading: 3
  trailing: 3
  slidingwindow: [4,15]
  minlen: 36
  adapter_fp: "/home/zhaoc1/miniconda3/envs/sunbeam/share/trimmomatic/adapters/NexteraPE-PE.fa"
  # Cutadapt
  fwd_adapters: []
  rev_adapters: []
  # Decontam.py
  pct_id: 0.5
  frac: 0.6
  keep_sam: False
  method: bwa
  human_genome_fp: "/mnt/isilon/microbiome/analysis/biodata/human_GRch38.fasta"
  phix_genome_fp: "/mnt/isilon/microbiome/analysis/biodata/phix174.fasta"


# Taxonomic classifications
classify:
  suffix: classify
  threads: 8
  kraken_db_fp: "/mnt/isilon/microbiome/analysis/biodata/krakendb/standard" # standard_erik
  taxa_db_fp: ""

# Contig assembly
assembly:
  suffix: assembly
  min_length: 300
  threads: 8
  cap3_fp: "/home/zhaoc1/sunbeam/local/CAP3"


# Contig annotation
annotation:
  suffix: annotation
  min_contig_len: 500
  circular_kmin: 10
  circular_kmax: 1000
  circular_min_len: 3500

  
# Blast databases
blast:
  threads: 8

blastdbs:
  root_fp: "/mnt/isilon/microbiome/analysis/biodata/blast"
  nucleotide:
    bacteria:
      BacterialGenomes/ncbi_bacteria.fa
    fungi:
      FungalGenomes/ncbi_fungi.fa
#    viral:
#      viral.1.1.genomic.fna
#    nt:
#      nt/nt
#  protein:
#    integrase:
#      UniprotPhageIntegrase.fasta
#    aclame:
#      ACLAME/aclame_proteins_viruses_prophages_0.4.fasta
#    vfdb:
#      VFDB/VFs.faa
#    card:
#      card/nucl_homolog.fasta

mapping:
  suffix: mapping
  threads: 8
  genomes_fp: "/mnt/isilon/microbiome/analysis/biodata/indexes"
  Rscript_fp: "/home/zhaoc1/sunbeam_neutrino/local/bin"
  # Pathfinder.py
  rapsearch_fp: "/home/zhaoc1/sunbeam_neutrino/local/RAPSearch2/bin"
  kegg_fp: "/mnt/isilon/microbiome/analysis/biodata/kegg"
  kegg_idx_fp: "/mnt/isilon/microbiome/analysis/biodata/keggRAP"
  kegg_to_ko_fp: "/mnt/isilon/microbiome/analysis/biodata/kegg2ko"
  genomes_fp: "/mnt/isilon/microbiome/analysis/biodata/fungalIndexes"
  bileacid_fp: "/mnt/isilon/microbiome/analysis/biodata/bileAcidsIndexes"
